###########################################################################
#								zing
#
#
###########################################################################

include ../../config.mk

CFLAGS = ${CFLAGS}

.PHONY : all clean


all:
	cd ${TARGET};make

clean:
	cd ${TARGET};make clean
